### PR TITLE
fix cache in a couple of places

### LINKED ISSUE #19: disable remapping on the opengl wrapoperation
it printed an warning for me on build

### PR DESCRIPTION
**Pull request by tildejustin**
changes:
- caches previous world when switching to next via bypass lock option
- restores the cache when leaving the queue from wall, as wall resets options when joining
  - semi-relevant for glitched, if quitting from wall screen, changing options in title screen will be reset upon rejoining. this shouldn't necessarily be encouraged, but i can't see any reason to not support it
- remap = false the new injector, closes #19

there's a good chance i missed something (and also working around mixinextras) so feel free to reimplement / fix however you like.

### CODE REVIEW

**Comment by tildejustin** [comment]
> StandardSettings restores the cache when actually joining a world, not on reset, could you elaborate on why this needs to be different for glitched?

for glitched, you typically increment rd from out of world before joining in for duping. in the case of leaving queue from the world without an accidental reset, you're going to go into the same world, so there is no cache to restore. in the case of an accidental reset to wall, a standardsettings reset will happen when opening wall, but if you leave queue from wall there's only one world you would ever go back to (assuming no double accidental reset), so we can restore that cache preemptively to allow editing settings on title screen and when going back into the world it won't revert those title screen changes. this will not affect normal users as standardsettings will reset on next world when they start atum again, and it is more intuitive because if you, say, change fov in a world, go to wall, shift esc, and join a server or practice map, the fov you set will be still be set since you haven't generated another world yet, and even though technically a standardsettings reset was called upon opening the wall screen, the user never has to know.

File: src/main/java/me/contaria/seedqueue/gui/wall/SeedQueueWallScreen.java [hunk 1]
```diff
@@ -454,6 +454,7 @@ public boolean keyPressed(int keyCode, int scanCode, int modifiers) {
 
         if (keyCode == GLFW.GLFW_KEY_ESCAPE && Screen.hasShiftDown()) {
             ModCompat.standardsettings$onWorldJoin();
```
Comment (KingContaria) [inline src/main/java/me/contaria/seedqueue/gui/wall/SeedQueueWallScreen.java:456]: This call to `ModCompat.standardsettings#onWorldJoin` should be removed, the cache load serves as its replacement.

**Review by KingContaria — CHANGES_REQUESTED** [review]
