### PR TITLE
Fix: Reset cooldown now applies to preparing seeds that move to main grid

### LINKED ISSUE #13: Reset cooldown doesn't reset when previews move
Pressing the reset all key twice in rapid succession will move previews into the main grid, then reset them even if they haven't been in the main grid for the Reset Cooldown period
This can be fixed by resetting the cooldownStart when instances are moved from preparing into main

### PR DESCRIPTION
**Pull request by Crystal15118**
Fixes #13 as reset cooldown is now also applied to preparing seeds that move to main grid.

### CODE REVIEW

File: src/main/java/me/contaria/seedqueue/gui/wall/SeedQueueWallScreen.java [hunk 1]
```diff
@@ -365,7 +365,9 @@ private void updateMainPreviews() {
                 break;
             }
             if (this.mainPreviews[i] == null && !this.blockedMainPositions.contains(i)) {
+                SeedQueuePreview preview = this.preparingPreviews.get(0);
                 this.mainPreviews[i] = this.preparingPreviews.remove(0);
+                preview.resetCooldown();
```
Comment (KingContaria) [inline src/main/java/me/contaria/seedqueue/gui/wall/SeedQueueWallScreen.java:370]: Could you change this to `this.mainPreviews[i].resetCooldown()`?

File: src/main/java/me/contaria/seedqueue/gui/wall/SeedQueuePreview.java [hunk 2]
```diff
@@ -202,6 +202,10 @@ public boolean isCooldownReady() {
         return System.currentTimeMillis() - this.cooldownStart >= SeedQueue.config.resetCooldown;
     }
 
+    public void resetCooldown() {
+        this.cooldownStart = System.currentTimeMillis();
```
Comment (KingContaria) [inline src/main/java/me/contaria/seedqueue/gui/wall/SeedQueuePreview.java:206]: Cooldown starts are meant to be populated in `SeedQueueWallScreen#populateResetCooldowns` because that method gets called after the new frame is actually rendered onto the screen instead of doing it during rendering. To reset the cooldown just set it to `Long.MAX_VALUE`, that will cause its cooldown to be repopulated at the end of the frame.

**Review by KingContaria — CHANGES_REQUESTED** [review]

File: src/main/java/me/contaria/seedqueue/gui/wall/SeedQueueWallScreen.java (hunk 1 above)
Comment (Crystal15118) [reply src/main/java/me/contaria/seedqueue/gui/wall/SeedQueueWallScreen.java]: > Could you change this to `this.mainPreviews[i].resetCooldown()`?

done :D

File: src/main/java/me/contaria/seedqueue/gui/wall/SeedQueuePreview.java (hunk 2 above)
Comment (Crystal15118) [reply src/main/java/me/contaria/seedqueue/gui/wall/SeedQueuePreview.java]: > Cooldown starts are meant to be populated in `SeedQueueWallScreen#populateResetCooldowns` because that method gets called after the new frame is actually rendered onto the screen instead of doing it during rendering. To reset the cooldown just set it to `Long.MAX_VALUE`, that will cause its cooldown to be repopulated at the end of the frame.

interesting (implemented changes)

**Review by KingContaria — APPROVED** [review]
Lgtm!

**Comment by KingContaria** [comment]
Gonna include in 1.1.1 hotfix
